- name: Set facts
  set_fact:
    color: "blue"
    host_port: "{{ '8081' if etype == 'pull_request' else '8080'}}"
    container_port: 8080
    container_name: "{{ 'colors-dev' if etype == 'pull_request' else 'colors' }}"
    
- name: Podman install
  become: true
  ansible.builtin.package:
    name: podman
    state: present
  
- name: Create a color container
    become: true
    containers.podman.podman_container:
      name: "{{ container_name }}"
      image: quay.io/acme_corp/eda-app:suncavanaugh
      state: started
      recreate: true
      network: bridge
      ports:
          - "{{ host_port }}:{{ container_port }}"
      env:
        APP_COLOR: "{{ color }}"

- name: Print container
    debug:
      var: container
