- name: pull_request -- Update application repository to event ref 
  ansible.builtin.git:
    repo: "{{ awx_webhook_payload.repository.clone_url }}"
    dest: "/tmp/{{ awx_webhook_payload.pull_request.head.ref }}"
    clone: true
    update: true
    version: "{{ awx_webhook_payload.pull_request.head.ref }}"
