- name: pull_request -- Update application repository to event ref 
  ansible.builtin.git:
    repo: "{{ ecloneurl }}"
    dest: "/tmp/{{ erepo }}"
    clone: true
    update: true
    version: "{{ eref }}"
