---
- name: push -- update application repo
  hosts: localhost
  gather_facts: false
  tasks:

  - name: push -- Clone application repository 
    ansible.builtin.git:
      repo: "{{ ecloneurl }}"
      dest: "/tmp/{{ erepo }}"
      clone: true
      update: true
