- name: push -- Clone application repository 
  ansible.builtin.git:
    repo: "{{ awx_webhook_payload.repository.clone_url }}"
    dest: "/tmp/{{ awx_webhook_payload.repository.name }}"
    clone: true
    update: true
