---
- name: Capture POSTs from git
  hosts: appnodes
  gather_facts: false
  tasks:

  - name: set facts
    set_fact:
      etype: "{{ awx_webhook_event_type }}"
      erepo: "{{ awx_webhook_payload.repository.name }}"
      eref: "{{ awx_webhook_payload.ref | split('/') | last }}"
      eauthor: "{{ awx_webhook_payload.pusher.name }}"
      ecloneurl: "{{ awx_webhook_payload.repository.clone_url }}"

  # Run action in response to push events
  - name: Respond to push event
    action:
      run_playbook:
        name: playbooks/on_push.yml
        post_events: true
    when: etype == "push"

  # Run action in response to push events
  - name: Respond to pull request event
    action:
      run_playbook:
        name: playbooks/on_pr.yml
        post_events: true
    when: etype == "pull_request"

  # Run action in response to push events
  - name: Deploy application
    action:
      run_playbook:
        name: /tmp/eda-app/deploy.yml
