---
- name: Capture POSTs from git
  hosts: appnodes
  gather_facts: false
  tasks:

  - name: set facts
    set_fact:
      etype: "{{ awx_webhook_event_type }}"
      erepo: "{{ awx_webhook_payload.repository.name }}"
      eref: "{{ awx_webhook_payload.ref | split('/') | last }}"
      eauthor: "{{ awx_webhook_payload.pusher.name }}"
      ecloneurl: "{{ awx_webhook_payload.repository.clone_url }}"

  # Run action in response to push events
  - name: Respond to push event
    import_playbook: playbooks/on_push.yml
    when: ansible_facts['etype'] == "push"

  # Run action in response to push events
  - name: Respond to pull request event
    import_playbook: playbooks/on_pr.yml
    when: ansible_facts['etype'] == "pull_request"

  # Run action in response to push events
  - name: Deploy application
    import_playbook: /tmp/eda-app/deploy.yml
